### PR TITLE
Move to 1.1.0 TES spec compliance

### LINKED ISSUE #254: [#7 TES 1.1 Spec compliance] Update TES compliance suite to 1.1
Update testing for TES compliance suite to 1.1

### LINKED ISSUE #479: Tes-compliance test failure - "Job to retrieve the service info"
**Describe the bug**
This bug is related to tes passing tes compliance tests defined in the following repo: https://github.com/elixir-cloud-aai/openapi-test-runner that checks to see if TES meets the G4GH TES API specification. The test suite is run as part of the tes release integration test in ADO, it is run for every release so you can always go see its results. As of today's report the following test is failing: 

tests/service_info.yml -- https://github.com/elixir-cloud-aai/openapi-test-runner/blob/dev/tests/service_info.yml
Job to retrieve the service info
Retrieve the TES server info
 "cases": [
2023-10-23T21:40:37.7124299Z                         {
2023-10-23T21:40:37.7124631Z                             "case_name": "status_code",
2023-10-23T21:40:37.7125304Z                             "case_description": "Check if response status code is 200",
2023-10-23T21:40:37.7125989Z                             "log_messages": [
2023-10-23T21:40:37.7126392Z                                 "No logs for success"
2023-10-23T21:40:37.7126856Z                             ],
2023-10-23T21:40:37.7127302Z                             "start_time": "2023-10-23T21:38:44Z",
2023-10-23T21:40:37.7127872Z                             "end_time": "2023-10-23T21:38:44Z",
2023-10-23T21:40:37.7128313Z                             "status": "PASS",
2023-10-23T21:40:37.7128935Z                             "message": "GET /service-info Successful Response status code"
2023-10-23T21:40:37.7129466Z                         },
2023-10-23T21:40:37.7129724Z                         {
2023-10-23T21:40:37.7130158Z                             "case_name": "response_schema_validation",
2023-10-23T21:40:37.7130674Z                             "case_description": "Check if response matches the model schema",
2023-10-23T21:40:37.7131159Z                             "log_messages": [
**2023-10-23T21:40:37.7132138Z                                 " validation errors for TesServiceInfo\nid\n  field required (type=value_error.missing)\ntype\n  field required (type=value_error.missing)\norganization\n  ..."**
2023-10-23T21:40:37.7133109Z                             ],
2023-10-23T21:40:37.7133493Z                             "start_time": "2023-10-23T21:38:44Z",
2023-10-23T21:40:37.7134000Z                             "end_time": "2023-10-23T21:38:44Z",
2023-10-23T21:40:37.7134383Z                             "status": "FAIL",
2023-10-23T21:40:37.7134952Z                             "message": "Response Schema validation failed for GET /service-info"
2023-10-23T21:40:37.7135424Z                         }
2023-10-23T21:40:37.7135648Z                     ]

**Expected behavior**
The 200 response needs to contain an id, as mentioned in the test: https://github.com/elixir-cloud-aai/openapi-test-runner/blob/dev/tests/service_info.yml

    response:
      200: |
        {
          "id": "uk.ac.ebi.tsc.tesk"
        }

### PR DESCRIPTION
**Pull request by vsmalladi**
* Add in  TES compliance suite to 1.1 and 1.0 
* Updated TES compliance suite to update the service info testing for email PR: https://github.com/elixir-cloud-aai/openapi-test-runner/pull/70 . This now allows our service info to pass for 1.0 and 1.1 compliance.

fixes #254
fixes #479

### CODE REVIEW

**Comment by vsmalladi** [comment]
Fixes #479

**Comment by yuliadub** [comment]
@vsmalladi according to ADO, all compliance tests [failed ](https://malibu00.visualstudio.com/Emmons/_releaseProgress?_a=release-environment-logs&releaseId=5761&environmentId=6715)--- @MattMcL4475 the error seems like the TES api was not reachable, did something change about how we connect to it? 

error: Exception Name - OS Error. Type - TestRunnerException. Message - Connection error to POST http://tes:***@tesinttest-53111467-5761-05994.southcentralus.cloudapp.azure.com/v1/tasks. Details - HTTPSConnectionPool(host='tesinttest-53111467-5761-05994.southcentralus.cloudapp.azure.com', port=443): Max retries exceeded with url: /v1/tasks (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self-signed certificate (_ssl.c:1135)')))

**Comment by BMurri** [comment]
> error: Exception Name - OS Error. Type - TestRunnerException. Message - Connection error to POST http://tes:***@tesinttest-53111467-5761-05994.southcentralus.cloudapp.azure.com/v1/tasks. Details - HTTPSConnectionPool(host='tesinttest-53111467-5761-05994.southcentralus.cloudapp.azure.com', port=443): Max retries exceeded with url: /v1/tasks (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self-signed certificate (_ssl.c:1135)')))

That means that the Certificate Manager in Kubernetes hasn't yet installed the LetsEncrypt certificate, which is definitely an environmental issue. However, by the time the compliance tests run, that cert should have been installed already. We get around that for the deployer's smoke test by using `kubectl`'s port forwarding feature. Maybe we need to do that for the compliance test too.

OTOH, not having a working certificate will prevent the deployment from being used by the end user, so the cert manager issue needs to be dealt with somehow.

**Comment by yuliadub** [comment]
> > error: Exception Name - OS Error. Type - TestRunnerException. Message - Connection error to POST http://tes:***@tesinttest-53111467-5761-05994.southcentralus.cloudapp.azure.com/v1/tasks. Details - HTTPSConnectionPool(host='tesinttest-53111467-5761-05994.southcentralus.cloudapp.azure.com', port=443): Max retries exceeded with url: /v1/tasks (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self-signed certificate (_ssl.c:1135)')))
> 
> That means that the Certificate Manager in Kubernetes hasn't yet installed the LetsEncrypt certificate, which is definitely an environmental issue. However, by the time the compliance tests run, that cert should have been installed already. We get around that for the deployer's smoke test by using `kubectl`'s port forwarding feature. Maybe we need to do that for the compliance test too.
> 
> OTOH, not having a working certificate will prevent the deployment from being used by the end user, so the cert manager issue needs to be dealt with somehow.

@BMurri thanks for the context. wonder if the failure was a random thing (something with the set up just didnt go right) - will try to rerun and see if that is still happening.

**Comment by vsmalladi** [comment]
@yuliadub any luck to see if this is fixed on a rerun?

**Comment by yuliadub** [comment]
@vsmalladi did you try to push an update to this PR to kick off another run? If not, I suggest you do. 

from looking at the test running on other branches, it is working: https://malibu00.visualstudio.com/Emmons/_releaseProgress?_a=release-environment-logs&releaseId=6229&environmentId=7183

**Comment by vsmalladi** [comment]
@yuliadub i have merged in main and tests are running now.

Below are 1.0.0 and 1.1.0 outputs

```
2024-05-17T17:32:13.0475620Z [0m
2024-05-17T17:32:13.0476013Z [33m############################################   Compliance Testing Summary   ############################################[0m
2024-05-17T17:32:13.0476409Z [33m#                                                                                                                      #[0m
2024-05-17T17:32:13.0476765Z [33m#                                                   Total Tests - 23                                                   #[0m
2024-05-17T17:32:13.0477195Z [33m#                        Passed - 16 (1, 2, 4, 5, 6, 7, 9, 10, 11, 12, 13, 15, 17, 20, 21, 22)                         #[0m
2024-05-17T17:32:13.0477905Z [33m#                                                    Failed - 0 ()                                                     #[0m
2024-05-17T17:32:13.0478306Z [33m#                                        Skipped - 7 (3, 8, 14, 16, 18, 19, 23)                                        #[0m
2024-05-17T17:32:13.0478690Z [33m#                                                                                                                      #[0m
2024-05-17T17:32:13.0479096Z [33m########################################################################################################################[0m
2024-05-17T17:32:13.0479309Z [33m
```

```
2024-05-17T17:36:18.8249703Z [33m############################################   Compliance Testing Summary   ############################################[0m
2024-05-17T17:36:18.8265191Z [33m#                                                                                                                      #[0m
2024-05-17T17:36:18.8265600Z [33m#                                                   Total Tests - 23                                                   #[0m
2024-05-17T17:36:18.8266022Z [33m#                 Passed - 20 (1, 2, 3, 4, 5, 6, 7, 9, 10, 11, 12, 13, 14, 15, 16, 18, 19, 20, 21, 22)                 #[0m
2024-05-17T17:36:18.8266407Z [33m#                                                Failed - 3 (8, 17, 23)                                                #[0m
2024-05-17T17:36:18.8266743Z [33m#                                                    Skipped - 0 ()                                                    #[0m
2024-05-17T17:36:18.8267064Z [33m#                                                                                                                      #[0m
2024-05-17T17:36:18.8267412Z [33m########################################################################################################################[0m
```

Tests failing now:

* create_task_ignore_error.yml 
* list_tasks_full.yml
* filter_task_by_tag.yml: [failed test]:(https://github.com/elixir-cloud-aai/openapi-test-runner/blob/17d44d7874d41cef30b0bef546b32f20596d499a/tests/filter_task_by_tag.yml#L55)

The other two fail due to a response return. That should be solved by PR #664

**Comment by vsmalladi** [comment]
@yuliadub yes I had to update the compliance tests with this PR https://github.com/elixir-cloud-aai/openapi-test-runner/pull/70

THat is now merged in so now Service info passes as part of the tests.

**Comment by yuliadub** [comment]
@vsmalladi I see - so the error was on the compliance test side, not us - I am sorry I totally missed that part. if that is the case, looks good to me. (a brief summary of all that in this PR could have helped clear that up vs just links to the issues, although now I do see the link to the elixir PR in one of the issue comments that I missed earlier)

**Review by yuliadub — APPROVED** [review]

**Comment by vsmalladi** [comment]
@yuliadub thanks updated the summary.

**Pull request merged**
