### PR TITLE
Moved resources/resource-quota endpoints from TerraLandingZoneApiClient to TerraWsmApiClient

### LINKED ISSUE #528: Implement Terra quota and resource GET requests in TerraWsmApiClient rather than TerraLandingZoneApiClient
**Problem:**
Terra Workspace Manager has moved to deprecate the endpoints 

- `/api/landingzones/v1/azure/{landingZoneId}/resource-quota` 
- `/api/landingzones/v1/azure/{landingZoneId}/resources` 

in favor of 
- `/api/workspaces/v1/{workspaceId}/resources/controlled/azure/landingzone/quota`
- `/api/workspaces/v1/{workspaceId}/resources/controlled/azure/landingzone`

The change is a result of Terra allowing workspace owners to share their workspaces with users who may not have a billing project (and by extension a landing zone) associated with their account. Outside of the new id requirement, behavior/payload remains unchanged.

**Solution:**
Essentially moved the logic of the previous landing zone methods over to the WSM client, making sure to update class definitions, tests, and object instantiation calls as needed. A PR has been opened at https://github.com/microsoft/ga4gh-tes/pull/523 to address the issue.

**Describe alternatives you've considered**
None, shift in preferred endpoints limits implementation strategies.

**Code dependencies**
Terra will require some code changes in its infrastructure (helm, internal app version references, etc.) to ensure that TES pods are deployed with the image that carries these changes (Terra/Broad dev responsibility).

### PR DESCRIPTION
**Pull request by JVThomas**
Quote from the WSM ticket that spurred this change...

_For multi user workflows (in Terra), users that are not part of the billing project and therefore do not have access to the landing zone will nonetheless need to be able to fetch batch pool quota (technically TES uses this endpoint in the data plane during workflow execution). The endpoint it has been querying is_ `/api/landingzones/v1/azure/{landingZoneId}/resource-quota` _which requires landing-zone permissions._

To address this,  two new endpoints were added to WSM

1. `/api/workspaces/v1/{workspaceId}/resources/controlled/azure/landingzone/quota` that mimics the behavior of `/api/landingzones/v1/azure/{landingZoneId}/resource-quota`
2. `/api/workspaces/v1/{workspaceId}/resources/controlled/azure/landingzone` that mimics the behavior of `/api/landingzones/v1/azure/{landingZoneId}/resources`

Since the behavior is the same (even the response payload), it's just a matter of moving the method from `TerraLandingZoneApiClient` over to `TerraWsmApiClient` (alongside class and test updates). The `TerraLandingZoneApiClient` was also removed since there's nothing left in it outside of a landing zone endpoint check.

I haven't been able to test it on Terra yet since I'm currently trying to figure out why my locally built TES image (of any kind, including `main`, `tags/4.6.0`, `tags/4.7.0`) isn't running tasks when deployed (it does queue the task though), so I figured I can at least submit this PR and get some eyes and feedback on the code while I work on that issue.

fixes #528

### CODE REVIEW

**Comment by JVThomas** [comment]
@microsoft-github-policy-service agree company="Broad Institute"

**Comment by BMurri** [comment]
@JVThomas Due to #519, when creating a local image of TES you need to publish `Tes.RunnerCLI` and copy, at minimum, the `tes-runner` and `tes-runner.md5` files into the `scripts` directory of TES's published build before creating the docker image (I don't believe the current Dockerfiles do that today as it depends on the relative layout of the various published outputs which we don't enforce in the repo). Something similar is required (with possibly different but likely easy to recognize file names) for builds using recent released tags.

It's on my TODO list to get that documented in the [Wiki](https://github.com/microsoft/ga4gh-tes/wiki) really soon.

**Comment by BMurri** [comment]
@JVThomas for the next couple of days or so, you can use `cromwellonazure/tes:int-5.0.1.9108` which is the current state of this PR's code if that helps you.

**Comment by JVThomas** [comment]
Thanks for the quick feedback @BMurri! Used your image and I can confirm that the new endpoints were hit successfully via WSM logs. 

Outside of a code review (new to C#, want to make sure the changes meet your team's standards), the only pending issue is the failed format check. I'm not seeing any files being formatted when running `dotnet format --verbosity detailed` locally, so is it just failing on the Azure CLI Login step?

**Comment by BMurri** [comment]
> Outside of a code review (new to C#, want to make sure the changes meet your team's standards), the only pending issue is the failed format check. I'm not seeing any files being formatted when running `dotnet format --verbosity detailed` locally, so is it just failing on the Azure CLI Login step?

Yes. That one check tries to log into something using a secret your repo doesn't have. I don't recall what that was for but we should probably remove that login because we are not automatically fixing formatting, just checking for it.

**Comment by BMurri** [comment]
@JVThomas could you please open an issue in this repo describing why this PR is needed? Either `Bug report` or `Feature request` template is fine, whichever seems easier to accommodate the reasons for the WSM ticket/new APIs, then either you or I can point this PR to that new issue, and I'll connect that issue up and merge this PR on your behalf (and you'll get the credit!)

**Comment by JVThomas** [comment]
@BMurri I've created an issue and referenced it in this PR (and vice versa). If there's any issues or if there's things to add, let me know!

**Review by BMurri — APPROVED** [review]

**Comment by BMurri** [comment]
@JVThomas Congratulations on your first code contribution to our TES project.

Thank you!

**Pull request merged**
